services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/New_York}
      - PLEX_CLAIM=${PLEX_CLAIM:-}
      - VERSION=docker
    volumes:
      - ./appdata/plex:/config
      - ./media/tv:/tv
      - ./media/movies:/movies
    ports:
      - "32400:32400"
      - "1900:1900/udp"
      - "3005:3005"
      # NOTE: UDP 5353 (mDNS) is frequently already in-use on Windows.
      # If you need LAN discovery features, free the port and re-enable this mapping.
      # - "5353:5353/udp"
      - "8324:8324"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/New_York}
    volumes:
      - ./appdata/sonarr:/config
      - ./media/tv:/tv
      - ./downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/New_York}
    volumes:
      - ./appdata/radarr:/config
      - ./media/movies:/movies
      - ./downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped

  setup-ui:
    build: ./setup-ui
    container_name: eden-setup-ui
    ports:
      - "8080:8080"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Los_Angeles}
      - SETUP_UI_PORT=8080
      - SETUP_UI_FIRST_RUN=${SETUP_UI_FIRST_RUN:-false}
      - CONFIG_PATH=/config/config.json
    volumes:
      - ${APPDATA_PATH:-./appdata}/setup-ui:/config
    restart: unless-stopped
